#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Empty workspace API testv2
on:
  push:
    branches:
      - 'investigate-passing-secrets-workflow-problem'
    paths:
      - '.github/workflows/empty-worksapce-smoke-test-on-minikube-2.yaml'

env:
   USERSTORY: CloneGitRepoAPI
   TS_API_TEST_KUBERNETES_COMMAND_LINE_TOOL: kubectl
   DEPLOYMENT_TIMEOUT: 90s

jobs:
  workspace-api-tests-on-minikube:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: investigate-passing-secrets-workflow-problem

    - name: Build base image
      run: |
        cd base/ubi8 && docker buildx build --platform linux/amd64 -t quay.io/devfile/base-developer-image:ubi8-latest .
        docker login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} quay.io

    # - name: Start minikube cluster
    #   id: run-minikube
    #   uses: che-incubator/setup-minikube-action@next
    #   with:
    #     minikube-version: v1.23.2

    # - name: Build universal image
    #   run: |
    #     echo "${GITHUB_SHA::6}"
    #     eval $(minikube -p minikube docker-env)
    #     cd universal/ubi8 && docker buildx build --platform linux/amd64 -t quay.io/devfile/universal-developer-image:${GITHUB_SHA::6} .

    # - name: Checkout WTO
    #   uses: actions/checkout@master
    #   with:
    #     repository: devfile/devworkspace-operator
    #     path: devworkspace-operator

    # - name: Checkout tests codebase
    #   uses: actions/checkout@master
    #   with:
    #     ref: api-test-with-clone-project-without-generating
    #     repository: eclipse/che
    #     path: che

    # - name: Install NodeJs
    #   uses: actions/setup-node@v3


    # - name: Pre-pull image on minikube
    #   run: |
    #     minikube image ls

    # - name: Setup cert manager
    #   run: |
    #     cd devworkspace-operator
    #     make install_cert_manager
    #     kubectl wait deployment -n cert-manager cert-manager --for condition=Available=True --timeout=$DEPLOYMENT_TIMEOUT
    #     kubectl wait deployment -n cert-manager cert-manager-cainjector --for condition=Available=True --timeout=$DEPLOYMENT_TIMEOUT
    #     kubectl wait deployment -n cert-manager cert-manager-webhook --for condition=Available=True --timeout=$DEPLOYMENT_TIMEOUT

    # - name: Setup DWO
    #   run: |
    #     cd devworkspace-operator
    #     make install



    # - name: Run Empty workspace smoke test
    #   run: |
    #     export TS_API_TEST_UDI_IMAGE=quay.io/devfile/universal-developer-image:ubi8-${GITHUB_SHA::6}
    #     cd che/tests/e2e
    #     npm i
    #     npm run driver-less-test

